[package]
name = "tdgrand"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
grammers-tl-parser = "1.0"
tdgrand-tl-gen = { path = "../tdgrand-tl-gen", version = "0.1" }
