[package]
name = "tdgrand-tl-parser"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2018"

[dependencies]
crc32fast = "1.2.1"

[dev-dependencies]
toml = "0.5.8"
