name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install tdlib
        run: |
          wget https://github.com/melix99/tdjson-ci/releases/download/1.8.2-1/tdjson-x86_64.zip
          unzip tdjson-x86_64
          sudo install -d /app/lib/pkgconfig
          sudo install -D libtdjson.so.* /app/lib
          sudo install -D pkgconfig/* /app/lib/pkgconfig
      - name: Run cargo build
        run: PKG_CONFIG_PATH=/app/lib/pkgconfig cargo build

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
